version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
#      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 41773:1972
      - 427733:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
